<?php

return [
    [0.01,"um centavo"], 
    [0.02,"dois centavos"],
    [0.03,"três centavos"],
    [0.04,"quatro centavos"],
    [0.05,"cinco centavos"],
    [0.06,"seis centavos"],
    [0.07,"sete centavos"],
    [0.08,"oito centavos"],
    [0.09,"nove centavos"],
    [0.1,"dez centavos"],
    [0.11,"onze centavos"],
    [0.12,"doze centavos"],
    [0.13,"treze centavos"],
    [0.14,"catorze centavos"],
    [0.15,"quinze centavos"],
    [0.16,"dezesseis centavos"],
    [0.17,"dezessete centavos"],
    [0.18,"dezoito centavos"],
    [0.19,"dezenove centavos"],
    [0.2,"vinte centavos"],
    [0.21,"vinte e um centavos"],
    [0.22,"vinte e dois centavos"],
    [0.23,"vinte e três centavos"],
    [0.24,"vinte e quatro centavos"],
    [0.25,"vinte e cinco centavos"],
    [0.26,"vinte e seis centavos"],
    [0.27,"vinte e sete centavos"],
    [0.28,"vinte e oito centavos"],
    [0.29,"vinte e nove centavos"],
    [0.3,"trinta centavos"],
    [0.31,"trinta e um centavos"],
    [0.32,"trinta e dois centavos"],
    [0.33,"trinta e três centavos"],
    [0.34,"trinta e quatro centavos"],
    [0.35,"trinta e cinco centavos"],
    [0.36,"trinta e seis centavos"],
    [0.37,"trinta e sete centavos"],
    [0.38,"trinta e oito centavos"],
    [0.39,"trinta e nove centavos"],
    [0.4,"quarenta centavos"],
    [0.41,"quarenta e um centavos"],
    [0.42,"quarenta e dois centavos"],
    [0.43,"quarenta e três centavos"],
    [0.44,"quarenta e quatro centavos"],
    [0.45,"quarenta e cinco centavos"],
    [0.46,"quarenta e seis centavos"],
    [0.47,"quarenta e sete centavos"],
    [0.48,"quarenta e oito centavos"],
    [0.49,"quarenta e nove centavos"],
    [0.5,"cinquenta centavos"],
    [0.51,"cinquenta e um centavos"],
    [0.52,"cinquenta e dois centavos"],
    [0.53,"cinquenta e três centavos"],
    [0.54,"cinquenta e quatro centavos"],
    [0.55,"cinquenta e cinco centavos"],
    [0.56,"cinquenta e seis centavos"],
    [0.57,"cinquenta e sete centavos"],
    [0.58,"cinquenta e oito centavos"],
    [0.59,"cinquenta e nove centavos"],
    [0.6,"sessenta centavos"],
    [0.61,"sessenta e um centavos"],
    [0.62,"sessenta e dois centavos"],
    [0.63,"sessenta e três centavos"],
    [0.64,"sessenta e quatro centavos"],
    [0.65,"sessenta e cinco centavos"],
    [0.66,"sessenta e seis centavos"],
    [0.67,"sessenta e sete centavos"],
    [0.68,"sessenta e oito centavos"],
    [0.69,"sessenta e nove centavos"],
    [0.70,"setenta centavos"],
    [0.71,"setenta e um centavos"],
    [0.72,"setenta e dois centavos"],
    [0.73,"setenta e três centavos"],
    [0.74,"setenta e quatro centavos"],
    [0.75,"setenta e cinco centavos"],
    [0.76,"setenta e seis centavos"],
    [0.77,"setenta e sete centavos"],
    [0.78,"setenta e oito centavos"],
    [0.79,"setenta e nove centavos"],
    [0.8,"oitenta centavos"],
    [0.81,"oitenta e um centavos"],
    [0.82,"oitenta e dois centavos"],
    [0.83,"oitenta e três centavos"],
    [0.84,"oitenta e quatro centavos"],
    [0.85,"oitenta e cinco centavos"],
    [0.86,"oitenta e seis centavos"],
    [0.87,"oitenta e sete centavos"],
    [0.88,"oitenta e oito centavos"],
    [0.89,"oitenta e nove centavos"],
    [0.9,"noventa centavos"],
    [0.91,"noventa e um centavos"],
    [0.92,"noventa e dois centavos"],
    [0.93,"noventa e três centavos"],
    [0.94,"noventa e quatro centavos"],
    [0.95,"noventa e cinco centavos"],
    [0.96,"noventa e seis centavos"],
    [0.97,"noventa e sete centavos"],
    [0.98,"noventa e oito centavos"],
    [0.99,"noventa e nove centavos"],
];
